targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          include:
            - lib/src/**
        options:
          preamble: // coverage:ignore-file
          ignore_for_file:
            - duplicate_ignore
