format: true
nullable-getter: false
synthetic-package: false
arb-dir: lib/src/shared/l10n/infra
output-dir: lib/src/shared/l10n/domain
template-arb-file: l10n_en.arb
output-localization-file: l10n.dart
output-class: L10n
