name: samples
description: 'flutter samples.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  drift: ^2.26.0
  drift_dev: ^2.26.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  sqlite3_flutter_libs: ^0.5.32

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
