name: samples
description: 'flutter samples.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  package_info_plus: ^8.1.4
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
