name: samples
description: 'flutter samples.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  flutter_riverpod: ^2.6.1
  flutter_timezone: ^4.1.0
  riverpod_annotation: ^2.6.1
  timezone: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
