name: samples

on: [push]

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: ""
      flutter_version: ""
      setup: |
        sudo apt update
        sudo apt install -y sqlite3 libsqlite3-dev
